// <auto-generated />
using System;
using BITS.Signage.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BITS.Signage.Infrastructure.Migrations
{
    [DbContext(typeof(BitsSignageDbContext))]
    [Migration("20260210072937_Phase0_3_ContentPlaylistSchedule")]
    partial class Phase0_3_ContentPlaylistSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Asset", b =>
                {
                    b.Property<string>("AssetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CdnUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("HeightPixels")
                        .HasColumnType("integer");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ScopeVenueId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WidthPixels")
                        .HasColumnType("integer");

                    b.HasKey("AssetId");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("ScopeVenueId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.ContentGroup", b =>
                {
                    b.Property<string>("ContentGroupId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DraftVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ScopeVenueId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ContentGroupId");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("ScopeVenueId");

                    b.HasIndex("TenantId");

                    b.ToTable("ContentGroups");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.ContentGroupItem", b =>
                {
                    b.Property<string>("ContentGroupItemId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ChildGroupId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContentGroupId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ContentGroupItemId");

                    b.HasIndex("AssetId");

                    b.HasIndex("ChildGroupId");

                    b.HasIndex("ContentGroupId");

                    b.ToTable("ContentGroupItems");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.ContentGroupPublished", b =>
                {
                    b.Property<string>("ContentGroupPublishedId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContentGroupId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("integer");

                    b.HasKey("ContentGroupPublishedId");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("ContentGroupId", "PublishedVersion")
                        .IsUnique();

                    b.ToTable("ContentGroupPublisheds");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.ContentGroupPublishedItem", b =>
                {
                    b.Property<string>("ContentGroupPublishedItemId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ChildGroupId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ChildGroupPublishedVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ContentGroupId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContentGroupPublishedId")
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("ContentGroupPublishedItemId");

                    b.HasIndex("AssetId");

                    b.HasIndex("ChildGroupId");

                    b.HasIndex("ContentGroupId");

                    b.HasIndex("ContentGroupPublishedId");

                    b.ToTable("ContentGroupPublishedItems");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("AutoRelaunch")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("KeepAwake")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LaunchOnBoot")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrimaryGroupId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RunMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("WatchdogReturnToForeground")
                        .HasColumnType("boolean");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("PrimaryGroupId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("VenueId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceAuthToken", b =>
                {
                    b.Property<string>("DeviceAuthTokenId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("DeviceAuthTokenId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("DeviceAuthTokens");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceCommand", b =>
                {
                    b.Property<string>("CommandId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedByUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("text");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("TimeoutAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CommandId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IssuedAtUtc");

                    b.HasIndex("IssuedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TimeoutAtUtc");

                    b.ToTable("DeviceCommands");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceEvent", b =>
                {
                    b.Property<string>("DeviceEventId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("EventTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("DeviceEventId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EventType");

                    b.HasIndex("Severity");

                    b.ToTable("DeviceEvents");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceGroup", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("GroupId");

                    b.HasIndex("VenueId");

                    b.ToTable("DeviceGroups");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DevicePairing", b =>
                {
                    b.Property<string>("PairingId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClaimedByUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClaimedTenantId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClaimedVenueId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceHardwareId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PairingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResultingDeviceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PairingId");

                    b.HasIndex("ClaimedByUserId");

                    b.HasIndex("ClaimedTenantId");

                    b.HasIndex("ClaimedVenueId");

                    b.HasIndex("DeviceHardwareId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("PairingCode")
                        .IsUnique();

                    b.HasIndex("ResultingDeviceId");

                    b.HasIndex("Status");

                    b.ToTable("DevicePairings");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceStatus", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("BatteryLevelPercent")
                        .HasColumnType("integer");

                    b.Property<int>("CachedAssetCount")
                        .HasColumnType("integer");

                    b.Property<long>("CachedBytesUsed")
                        .HasColumnType("bigint");

                    b.Property<long?>("CurrentManifestEpoch")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrentPlaylistId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CurrentPlaylistVersion")
                        .HasColumnType("integer");

                    b.Property<long?>("FreeDiskSpaceBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("FreeStorageBytesLocal")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPlaybackErrorAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastPlaybackErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("PlaybackErrorCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("WifiSignalStrengthDbm")
                        .HasColumnType("integer");

                    b.HasKey("DeviceId");

                    b.HasIndex("IsOnline");

                    b.HasIndex("LastHeartbeatAtUtc");

                    b.HasIndex("VenueId");

                    b.ToTable("DeviceStatuses");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.EditorPresence", b =>
                {
                    b.Property<string>("PresenceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PresenceId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "ResourceType", "ResourceId");

                    b.ToTable("EditorPresences");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Playlist", b =>
                {
                    b.Property<string>("PlaylistId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DraftVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ScopeVenueId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlaylistId");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("ScopeVenueId");

                    b.HasIndex("TenantId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.PlaylistItem", b =>
                {
                    b.Property<string>("PlaylistItemId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContentGroupId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlaylistItemId");

                    b.HasIndex("AssetId");

                    b.HasIndex("ContentGroupId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("PlaylistItems");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.PlaylistPublished", b =>
                {
                    b.Property<string>("PlaylistPublishedId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistPublishedId");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("PlaylistId", "PublishedVersion")
                        .IsUnique();

                    b.ToTable("PlaylistPublisheds");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.PlaylistPublishedItem", b =>
                {
                    b.Property<string>("PlaylistPublishedItemId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlaylistPublishedId")
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("SourceContentGroupId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SourceContentGroupVersion")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistPublishedItemId");

                    b.HasIndex("AssetId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("PlaylistPublishedId");

                    b.HasIndex("SourceContentGroupId");

                    b.ToTable("PlaylistPublishedItems");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.PublishEvent", b =>
                {
                    b.Property<string>("PublishEventId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PropagatedPlaylistIds")
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("PublishEventId");

                    b.HasIndex("EntityId");

                    b.HasIndex("PublishedAtUtc");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Type");

                    b.HasIndex("VenueId");

                    b.ToTable("PublishEvents");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.SchedulePublished", b =>
                {
                    b.Property<string>("SchedulePublishedId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("integer");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VenueScheduleSetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SchedulePublishedId");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("VenueScheduleSetId", "PublishedVersion")
                        .IsUnique();

                    b.ToTable("SchedulePublisheds");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.SchedulePublishedSlot", b =>
                {
                    b.Property<string>("SchedulePublishedSlotId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DaysOfWeekMask")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("EndMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SchedulePublishedId")
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StartMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("ValidFromDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidToDate")
                        .HasColumnType("date");

                    b.Property<string>("VenueScheduleSetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SchedulePublishedSlotId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SchedulePublishedId");

                    b.HasIndex("VenueScheduleSetId", "PublishedVersion");

                    b.ToTable("SchedulePublishedSlots");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.ScheduleSlot", b =>
                {
                    b.Property<string>("SlotId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysOfWeekMask")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("EndMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("StartMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ValidFromDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidToDate")
                        .HasColumnType("date");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VenueScheduleSetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SlotId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TargetId");

                    b.HasIndex("VenueId");

                    b.HasIndex("VenueScheduleSetId");

                    b.HasIndex("VenueId", "DaysOfWeekMask", "StartMinutes", "EndMinutes");

                    b.ToTable("ScheduleSlots");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Tenant", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultTimezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.TenantUserRole", b =>
                {
                    b.Property<string>("TenantUserRoleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TenantUserRoleId");

                    b.HasIndex("Role");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("TenantUserRoles");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Venue", b =>
                {
                    b.Property<string>("VenueId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FallbackPlaylistId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VenueId");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("TenantId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.VenueEpoch", b =>
                {
                    b.Property<string>("VenueId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("ManifestEpoch")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VenueId");

                    b.ToTable("VenueEpochs");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.VenueScheduleSet", b =>
                {
                    b.Property<string>("VenueScheduleSetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DraftVersion")
                        .HasColumnType("integer");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("VenueScheduleSetId");

                    b.HasIndex("VenueId");

                    b.ToTable("VenueScheduleSets");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.VenueUserRole", b =>
                {
                    b.Property<string>("VenueUserRoleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("VenueUserRoleId");

                    b.HasIndex("Role");

                    b.HasIndex("UserId");

                    b.HasIndex("VenueId", "UserId")
                        .IsUnique();

                    b.ToTable("VenueUserRoles");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.ContentGroupItem", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.ContentGroup", "ChildGroup")
                        .WithMany()
                        .HasForeignKey("ChildGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.ContentGroup", "ContentGroup")
                        .WithMany("DraftItems")
                        .HasForeignKey("ContentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("ChildGroup");

                    b.Navigation("ContentGroup");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.ContentGroupPublished", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.ContentGroup", "ContentGroup")
                        .WithMany("PublishedVersions")
                        .HasForeignKey("ContentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BITS.Signage.Domain.Entities.User", "PublishedByUser")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentGroup");

                    b.Navigation("PublishedByUser");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.ContentGroupPublishedItem", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.ContentGroup", "ChildGroup")
                        .WithMany()
                        .HasForeignKey("ChildGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.ContentGroup", "ContentGroup")
                        .WithMany()
                        .HasForeignKey("ContentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BITS.Signage.Domain.Entities.ContentGroupPublished", null)
                        .WithMany("Items")
                        .HasForeignKey("ContentGroupPublishedId");

                    b.Navigation("Asset");

                    b.Navigation("ChildGroup");

                    b.Navigation("ContentGroup");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Device", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.DeviceGroup", "PrimaryGroup")
                        .WithMany("Devices")
                        .HasForeignKey("PrimaryGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.Venue", "Venue")
                        .WithMany("Devices")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryGroup");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceAuthToken", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Device", "Device")
                        .WithMany("AuthTokens")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceCommand", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BITS.Signage.Domain.Entities.User", "IssuedByUser")
                        .WithMany()
                        .HasForeignKey("IssuedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("IssuedByUser");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceEvent", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceGroup", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Venue", "Venue")
                        .WithMany("DeviceGroups")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DevicePairing", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.User", "ClaimedByUser")
                        .WithMany()
                        .HasForeignKey("ClaimedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.Tenant", "ClaimedTenant")
                        .WithMany()
                        .HasForeignKey("ClaimedTenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.Venue", "ClaimedVenue")
                        .WithMany()
                        .HasForeignKey("ClaimedVenueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.Device", "ResultingDevice")
                        .WithMany()
                        .HasForeignKey("ResultingDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClaimedByUser");

                    b.Navigation("ClaimedTenant");

                    b.Navigation("ClaimedVenue");

                    b.Navigation("ResultingDevice");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceStatus", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.EditorPresence", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.PlaylistItem", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.ContentGroup", "ContentGroup")
                        .WithMany()
                        .HasForeignKey("ContentGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.Playlist", "Playlist")
                        .WithMany("DraftItems")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("ContentGroup");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.PlaylistPublished", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Playlist", "Playlist")
                        .WithMany("PublishedVersions")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BITS.Signage.Domain.Entities.User", "PublishedByUser")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("PublishedByUser");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.PlaylistPublishedItem", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BITS.Signage.Domain.Entities.Playlist", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BITS.Signage.Domain.Entities.PlaylistPublished", null)
                        .WithMany("Items")
                        .HasForeignKey("PlaylistPublishedId");

                    b.HasOne("BITS.Signage.Domain.Entities.ContentGroup", "SourceContentGroup")
                        .WithMany()
                        .HasForeignKey("SourceContentGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("Playlist");

                    b.Navigation("SourceContentGroup");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.PublishEvent", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.User", "PublishedByUser")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublishedByUser");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.SchedulePublished", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.User", "PublishedByUser")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BITS.Signage.Domain.Entities.VenueScheduleSet", "VenueScheduleSet")
                        .WithMany("PublishedVersions")
                        .HasForeignKey("VenueScheduleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublishedByUser");

                    b.Navigation("VenueScheduleSet");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.SchedulePublishedSlot", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Playlist", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BITS.Signage.Domain.Entities.SchedulePublished", null)
                        .WithMany("Slots")
                        .HasForeignKey("SchedulePublishedId");

                    b.HasOne("BITS.Signage.Domain.Entities.VenueScheduleSet", "VenueScheduleSet")
                        .WithMany()
                        .HasForeignKey("VenueScheduleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("VenueScheduleSet");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.ScheduleSlot", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Playlist", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BITS.Signage.Domain.Entities.VenueScheduleSet", "VenueScheduleSet")
                        .WithMany("DraftSlots")
                        .HasForeignKey("VenueScheduleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("VenueScheduleSet");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.TenantUserRole", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Tenant", "Tenant")
                        .WithMany("UserRoles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BITS.Signage.Domain.Entities.User", "User")
                        .WithMany("TenantRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.User", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Venue", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Venues")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.VenueEpoch", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.VenueScheduleSet", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.VenueUserRole", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.User", "User")
                        .WithMany("VenueRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BITS.Signage.Domain.Entities.Venue", "Venue")
                        .WithMany("UserRoles")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.ContentGroup", b =>
                {
                    b.Navigation("DraftItems");

                    b.Navigation("PublishedVersions");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.ContentGroupPublished", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Device", b =>
                {
                    b.Navigation("AuthTokens");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceGroup", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Playlist", b =>
                {
                    b.Navigation("DraftItems");

                    b.Navigation("PublishedVersions");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.PlaylistPublished", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.SchedulePublished", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("Users");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.User", b =>
                {
                    b.Navigation("TenantRoles");

                    b.Navigation("VenueRoles");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Venue", b =>
                {
                    b.Navigation("DeviceGroups");

                    b.Navigation("Devices");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.VenueScheduleSet", b =>
                {
                    b.Navigation("DraftSlots");

                    b.Navigation("PublishedVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
