// <auto-generated />
using System;
using BITS.Signage.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BITS.Signage.Infrastructure.Migrations
{
    [DbContext(typeof(BitsSignageDbContext))]
    partial class BitsSignageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("AutoRelaunch")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("KeepAwake")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LaunchOnBoot")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrimaryGroupId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RunMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("WatchdogReturnToForeground")
                        .HasColumnType("boolean");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("PrimaryGroupId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("VenueId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceAuthToken", b =>
                {
                    b.Property<string>("DeviceAuthTokenId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("DeviceAuthTokenId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("DeviceAuthTokens");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceGroup", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("GroupId");

                    b.HasIndex("VenueId");

                    b.ToTable("DeviceGroups");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DevicePairing", b =>
                {
                    b.Property<string>("PairingId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClaimedByUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClaimedTenantId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClaimedVenueId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceHardwareId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PairingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResultingDeviceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PairingId");

                    b.HasIndex("ClaimedByUserId");

                    b.HasIndex("ClaimedTenantId");

                    b.HasIndex("ClaimedVenueId");

                    b.HasIndex("DeviceHardwareId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("PairingCode")
                        .IsUnique();

                    b.HasIndex("ResultingDeviceId");

                    b.HasIndex("Status");

                    b.ToTable("DevicePairings");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Tenant", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultTimezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.TenantUserRole", b =>
                {
                    b.Property<string>("TenantUserRoleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TenantUserRoleId");

                    b.HasIndex("Role");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("TenantUserRoles");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Venue", b =>
                {
                    b.Property<string>("VenueId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FallbackPlaylistId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VenueId");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("TenantId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.VenueUserRole", b =>
                {
                    b.Property<string>("VenueUserRoleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("VenueUserRoleId");

                    b.HasIndex("Role");

                    b.HasIndex("UserId");

                    b.HasIndex("VenueId", "UserId")
                        .IsUnique();

                    b.ToTable("VenueUserRoles");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Device", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.DeviceGroup", "PrimaryGroup")
                        .WithMany("Devices")
                        .HasForeignKey("PrimaryGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.Venue", "Venue")
                        .WithMany("Devices")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryGroup");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceAuthToken", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Device", "Device")
                        .WithMany("AuthTokens")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceGroup", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Venue", "Venue")
                        .WithMany("DeviceGroups")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DevicePairing", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.User", "ClaimedByUser")
                        .WithMany()
                        .HasForeignKey("ClaimedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.Tenant", "ClaimedTenant")
                        .WithMany()
                        .HasForeignKey("ClaimedTenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.Venue", "ClaimedVenue")
                        .WithMany()
                        .HasForeignKey("ClaimedVenueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BITS.Signage.Domain.Entities.Device", "ResultingDevice")
                        .WithMany()
                        .HasForeignKey("ResultingDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClaimedByUser");

                    b.Navigation("ClaimedTenant");

                    b.Navigation("ClaimedVenue");

                    b.Navigation("ResultingDevice");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.TenantUserRole", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Tenant", "Tenant")
                        .WithMany("UserRoles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BITS.Signage.Domain.Entities.User", "User")
                        .WithMany("TenantRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.User", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Venue", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Venues")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.VenueUserRole", b =>
                {
                    b.HasOne("BITS.Signage.Domain.Entities.User", "User")
                        .WithMany("VenueRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BITS.Signage.Domain.Entities.Venue", "Venue")
                        .WithMany("UserRoles")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Device", b =>
                {
                    b.Navigation("AuthTokens");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.DeviceGroup", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("Users");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.User", b =>
                {
                    b.Navigation("TenantRoles");

                    b.Navigation("VenueRoles");
                });

            modelBuilder.Entity("BITS.Signage.Domain.Entities.Venue", b =>
                {
                    b.Navigation("DeviceGroups");

                    b.Navigation("Devices");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
